### ISSUE TITLE
19_06_2020 | Team-104-the-fornax

### ISSUE THREAD

**Issue by rajkumardas2701** [OdongAlican/ror-social-scaffold#3]
Great work Team and superbly presented by Sunday today in Stand up call.

As discussed, you guys need to work on Test cases for the helper methods in the user model.
Also, as a suggestion, can we add an icon on the Navbar stating if you have any pending request (for easy access to the user)

**Comment by OdongAlican** [comment]
Thanks a lot for your feedback @rajkumardas2701. We have implemented the changes. Please feel free to take another look and give us feedback.
